### ISSUE TITLE
Idea: Build a similar integration for Veloretti e-bikes

### ISSUE THREAD

**Issue by jonskoglund** [elsbrock/cowboy-ha#61]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/elsbrock/cowboy-ha/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I sometimes forget to charge my bike battery. Would be nice to have home assistant notify me to charge. Or a reminder when I  need to bring my bike in for service (...after x kilometres send notification or every x months).

### Describe the solution you'd like

I'd like to see a similar integration for Veloretti e-bikes. Did a quick search for a Veloretti API but didn't find anything.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by elsbrock** [comment]
That looks like a nice bike!

It doesn’t seem like they have a public API either (like Cowboy), but since they have an App, it’s likely possible.

that being said, this integration is just for Cowboys, and I do not have access to a Veloretti. Hence, closing as not planned.
